import type { Metadata } from "next";

import Header from "@/components/header/Header";

import Language from "@/components/language/Language";

import "./globals.css";
import "./scroll.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      style={{
        scrollBehavior: "smooth",
      }}
      className={"dark"}
    >
      <body>
        <Header />
        <div className="page-content">{children}</div>
        <div>
          <Language />
        </div>
      </body>
    </html>
  );
}
