import type { Metadata } from "next";
import { useLocale } from "next-intl";
import { notFound } from "next/navigation";
import { redirect } from "next/navigation";

import Header from "@/components/header/Header";
import Language from "@/components/language/Language";

import "../globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface locale {
  locale: any;
}

const locales: string[] = ["en", "ru", "uk-ua"];

export default function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: locale;
}) {
  console.log(locale);

  const isValidLocale = locales.some((cur) => cur === locale);
  if (!isValidLocale) {
    // redirect("/", { locale: "en" });
  }

  return (
    <html
      lang={locale}
      style={{
        scrollBehavior: "smooth",
      }}
      className={"dark"}
    >
      <body>
        <Header />
        <div className="page-content">{children}</div>
        <div>
          <Language />
        </div>
      </body>
    </html>
  );
}
